### ISSUE TITLE
Security issue through preformance-now

### ISSUE THREAD

**Issue by antal-levente** [chrisdickinson/raf#44]
Hi,

In your dependencies theres this [performance-now](https://www.npmjs.com/package/performance-now ) package which has no Github page btw and wasn't touched since 4 years. This packages uses a deprecated coffee script version which is a security threat ( we were PEN tested recently and this came up there ).

To be honest this performance-now also doesn't looks okey, no Github page or any other, wasn't touched since years, etc.

Any chance for removing these in the future?

**Comment by ljharb** [comment]
In what way is it a "security threat"? There's no CVEs filed. Separately, "hasn't been touched in years" isn't necessarily a bad thing; some things are just finished and need no further updates.

**Comment by antal-levente** [comment]
Problem is that the Coffeescript version the package uses is deprecated. So no further support for it even though someone files a CVE. And because wasn't touched since years + theres no Github or any other page where the source can be checked, isn't that a flag? The source is at npm only.

**Comment by CMTegner** [comment]
Looks like coffee-script is listed in [performance-now's `devDependencies`](https://unpkg.com/performance-now@2.1.0/package.json). How is this supposed security issue affecting its dependents?

FWIW this is the [source code on GitHub](https://github.com/myrne/performance-now). I think the broken/wrong link on npm may be due to a user rename on GH. It almost looks like someone is squatting on the Braveg1rl GH user.

**Comment by antal-levente** [comment]
@CMTegner thanks for the information. Seems like then we have an issue in our build pipeline and somehow the devDependencies were installed on a production environment and PEN testers found that.

i'll close the issue for now.
